---
  - name: Writing a calculator
    become: yes
    hosts: localhost
    connection: local
    vars_prompt:
      - name: k
        prompt: Enter 'k' value 
      - name: b
        prompt: Enter 'b' value 
    vars:
      addition: "{{k|int+b|int}}"
      subtraction: "{{k|int-b|int}}"
      multiplication: "{{k|int*b|int}}"
      division: "{{k|int/b|int}}"
      percent: "{{k|int%b|int}}"
    gather_facts: false 
    tasks:
      - name: displaying arithematic results 
        ansible.builtin.debug:
          msg:
            - "k value is: {{k}} and b value is {{b}}"
            - "Addition is {{addition}}"
            - "Subtraction is {{subtraction}}"
            - "Multiplication is {{multiplication}}"
            - "Division is {{division}}"
            - "Percentags is {{percent}}"
