---
- name: Java Version
  become: yes
  hosts: "{{targets}}"
  connection: ssh
  gather_facts: false
  tasks:
    - name: Checking java Version
      ansible.builtin.shell: 'javac --version'
      register: javaversion
    - name: Display Version
      ansible.builtin.debug:
        msg: "{{ javaversion.stderr, javaversion.rc }}"
