---
- name: Java Version
  become: yes
  hosts: "{{targets}}"
  connection: ssh
  gather_facts: false
  tasks:
    - name: Install Java on managed nodes
      ansible.builtin.dnf:
        name: openjdk-11-jdk
        update_cache: yes
        state: present
                
    - name: Checking java Version
      ansible.builtin.shell: 'java -version'
      register: javaversion
    - name: Display Version
      ansible.builtin.debug:
        msg: "{{ javaversion, javaversion.rc }}"
