---
-  name: Creating file
   hosts: all
   become: yes
   tasks:
   - name: Pinging remote servers 
     ansible.builtin.ping:
   - name: creating a file on remote servers
     ansible.builtin.file:
      path: /tmp/boot
      mode: 755
      state: touch 
       
