---
- name: Nginx
  hosts: dev
  connection: ssh
  become: yes
  become_user: root 
  become_method: sudo
  gather_facts: false
  tasks:
  - name: Install Nginx service 
    ansible.builtin.package:
      name: nginx
      state: present 
