---
  - name: Python Version
    become: yes
    hosts: localhost
    connection: local
    gather_facts: false
    tasks:
      - name: Checking python Version
        ansible.builtin.command: "python --version"
