---
  - name: Python Version
    become: yes
    hosts: "{{targets}}"
    connection: ssh
    gather_facts: false
    tasks:
      - name: Checking python Version
        ansible.builtin.shell: 'python3 --version'
        register: pythonversion
      - name: Display Version
        ansible.builtin.debug:
          msg: "{{ pythonversion.stdout, pythonversion.rc }}"
