---
  - name: Python Version
    become: yes
    hosts: localhost
    connection: local
    gather_facts: false
    tasks:
      - name: Checking python Version
        ansible.builtin.shell: 'python --version'
        register: pythonversion
      - name: Display Version
        ansible.builtin.debug:
          msg: "{{ pythonversion }}"
