---
- name: File creation
  hosts: localhost
  connection: local
  gather_facts: true

  tasks:
    - block:
        - name: Ensure demo files are there
          ansible.builtin.file:
            path: /tmp/demo.txt
            state: touch

        - name: Write some content
          ansible.builtin.copy:
            content: "Putting some content in that"
            dest: /tmp/demo.txt
            owner: ansadmin
            group: ansadmin
            mode: "0644"
      become: yes

      rescue:
        - name: Capturing log
          ansible.builtin.debug:
            msg: "file creation error on {{ inventory_hostname }}"

      always:
        - name: Capturing facts
          ansible.builtin.setup:
            filter: ansible_facts

        - name: Print facts
          ansible.bulitin.debug:
            msg: { { ansible_facts } }
