---
- name: File creation
  hosts: localhost
  connection: local
  become: yes
  gather_facts: true

  tasks:
    block:
      - name: Ensure demo files are there
        ansible.builtin.file:
          path: /tmp/demo.txt
          state: touch
        ignore_errors: true

      - name: Write some content
        ansible.builtin.copy:
          content: "Putting some content in that"
          dest: /tmp/demo.txt
          owner: ansadmin
          group: ansadmin
          mode: "0644"
        ignore_errors: true

    rescue:
      - name: Capturing log
        ansible.builtin.debug:
          msg: "file creation error on {{ inventory_hostname }}"
