---
- name: Install Nginx
  hosts: dev
  become: yes 
  connection: ssh 
  gather_facts: true 

  tasks:
  - name: Installing Nginx
    ansible.builtin.yum:
      name: nginx
      state: present 
      update_cache: yes
    when: ansible_facts['os_family'] == "Debian"
  
  # - name: Start Nginx 
  #   ansible.builtin.dnf:
  #     name: nginx
  #     state: started 