#update cache is used to refresh the system cache before installing any packages.
---
- name: Checking and creating user
  hosts: dev
  connection: local
  become: yes
  gather_facts: true
  tasks:
  - name: Installing packages on RHEL Family
    ansible.builtin.yum:
      name: mysql-server 
      state: present
      update_cache: true
    when: ansible_facts.os_family == "RedHat" 

  - name: Installing packages on Ubuntu Family
    ansible.builtin.apt:
      name: mysql-server 
      state: present
      update_cache: true
    when: ansible_facts.os_family == "Debian" 
  
  - name: To see the package managers 
    ansible.builtin.debug:
      msg: "{{ ansible_facts.pkg_mgr }}"