---
- name: Manag Docker service with error handling
  hosts: localhost
  connection: local
  become: yes
  gather_facts: true
  tasks:
    - name: Ensure docket service is handled
      block:
        - name: Install OpenSSH server on RHEL/CentOS
          ansible.builtin.dnf:
            name: openssh-server
            state: present
            update_cache: yes
          when: ansible_facts.os_family == "RedHat"

        - name: Start SSHD service
          ansible.builtin.service:
            name: sshd
            state: started
            enabled: true

      rescue:
        - name: log failure if SSHD setup fails
          ansible.builtin.debug:
            msg: "SSHD setup failed on {{ inventory_hostname }}"

      always:
        - name: Gather systemd facts
          ansible.builtin.setup:
            filter: ansible_systemd*

        - name: Show SSHD systemd facts
          ansible.builtin.debug:
            msg: ansible_systemd.services['sshd.service']

    - name: Gather service facts
      ansible.builtin.service_facts:

    - name: Check SSHD status
      ansible.builtin.debug:
        var: ansible_systemd.services['httpd..service']
