#Create a user only if they don't exist and send the result to a file on your laptop"
---
- name: Checking and creating user
  hosts: localhost
  connection: local
  become: yes
  gather_facts: yes
  tasks:
  - name: Check user exist or not 
    ansible.builtin.shell: "id -u ramdas > ./output.txt 2>&1"
    register: userstate
  # - name: create user
  #   ansible.builtin.command:
  #     cmd: " useradd ramdas "
  #   when: " '{{ userstate }} | int' >= 0 else useradd ramdas &>> output.txt"